const productos = [
    {
        id: 1,
        nombre: "CHICO X 3",
        precio: 1100,
        img: '../assets/imagenes/mixtos.jpg',
        cantidad:1,
    },
    {
        id: 2,
        nombre: "MEDIANO X 3",
        precio: 2900,
        img: '../assets/imagenes/mixtos.jpg',
        cantidad:1,
    },
    {
        id: 3,
        nombre: "GRANDE X 3",
        precio: 4100,
        img: '../assets/imagenes/mixtos.jpg',
        cantidad:1,
    },
    {
        id: 4,
        nombre: "SUPER X 3",
        precio: 6150,
        img: '../assets/imagenes/mixtos.jpg',
        cantidad:1,
    },
    {
        id: 5,
        nombre: "CHICO BLANCO",
        precio: 500,
        img: '../assets/imagenes/blancos.jpg',
        cantidad: 1,
    },
    {
        id: 6,
        nombre: "MEDIANO BLANCO",
        precio: 1000,
        img: '../assets/imagenes/blancos.jpg',
        cantidad: 1,
    },
    {
        id: 7,
        nombre: "GRANDE BLANCO",
        precio: 1500,
        img: '../assets/imagenes/blancos.jpg',
        cantidad: 1,
    },
    {
        id: 8,
        nombre: "SUPER BLANCO",
        precio: 2000,
        img: '../assets/imagenes/blancos.jpg',
        cantidad: 1,
    },
    {
        id: 9,
        nombre: "CHICO COLOR",
        precio: 600,
        img: '../assets/imagenes/color.jpg',
        cantidad: 1,
    },
    {
        id: 10,
        nombre: "MEDIANO COLOR",
        precio: 1100,
        img: '../assets/imagenes/color.jpg',
        cantidad: 1,
    },
    {
        id: 11,
        nombre: "GRANCE COLOR",
        precio: 1600,
        img: '../assets/imagenes/color.jpg',
        cantidad: 1,
    },
    {
        id: 12,
        nombre: "SUPER COLOR",
        precio: 2100,
        img: '../assets/imagenes/color.jpg',
        cantidad: 1,
    }
];